# Analiza i projektiranje računalom - 4. laboratorijska vježba: demo mutation.py

## Priprema za izvođenje

In [1]:
import os

CD_KEY = "--HW04_D05_IN_ROOT"

In [2]:
if (
    CD_KEY not in os.environ
    or os.environ[CD_KEY] is None
    or len(os.environ[CD_KEY]) == 0
    or os.environ[CD_KEY] == "false"
):
    %cd ..
else:
    print(os.getcwd())
    
os.environ[CD_KEY] = "true"

/mnt/data/projekti/faks/AIPR/dz/dz-04


## Učitavanje paketa

In [3]:
import numpy as np

from src.evolution.encoding import BinaryEncoder
from src.evolution.mutation import (
    GaussianMutation,
    StochasticCorruptionMutation,
)

## Inicijalizacija

### Formatiranje

In [4]:
np.set_printoptions(precision=2, suppress=True)

### Konstante

In [5]:
specimen_shape = (5,)

bits = 8
interval = (-1, 1)

n_repeats = 3

### Jedinke

In [6]:
specimen = np.random.uniform(*interval, specimen_shape)

### Koderi

In [7]:
be = BinaryEncoder(dim=8, interval=interval)

### Operatori

In [8]:
float_operators = [
    GaussianMutation(mutation_probability=0.5)
]
binary_operators = [
    StochasticCorruptionMutation(mutation_probability=0.5)
]

## Demonstracija

### Prikaz s pomičnom točkom

In [9]:
for float_operator in float_operators:
    print(f"Koristeći {float_operator}")
    
    for _ in range(n_repeats):
        print(f"{specimen} ->\n{float_operator(specimen)}")
        print()

Koristeći GaussianMutation operator
[-0.48  0.24  0.89  0.55  0.15] ->
[-0.48  0.18  0.89  0.55 -0.3 ]

[-0.48  0.24  0.89  0.55  0.15] ->
[0.56 0.91 0.89 0.55 0.15]

[-0.48  0.24  0.89  0.55  0.15] ->
[-0.48  0.24  1.89  1.56  1.34]



### Prikaz u binarnom obliku

In [10]:
for binary_operator in binary_operators:
    print(f"Koristeći {binary_operator}")
    
    for _ in range(n_repeats):
        print(f"{be(specimen)} ->\n{binary_operator(be(specimen))}")
        print()

Koristeći StochasticCorruptionMutation operator
[[0 1 0 0 0 0 1 0]
 [1 0 0 1 1 1 0 1]
 [1 1 1 1 0 0 0 0]
 [1 1 0 0 0 1 0 1]
 [1 0 0 1 0 0 1 1]] ->
[[0 0 1 1 1 0 0 1]
 [1 0 1 1 1 1 1 0]
 [0 1 0 0 1 1 0 0]
 [0 0 0 0 1 1 0 1]
 [1 0 0 1 0 1 1 0]]

[[0 1 0 0 0 0 1 0]
 [1 0 0 1 1 1 0 1]
 [1 1 1 1 0 0 0 0]
 [1 1 0 0 0 1 0 1]
 [1 0 0 1 0 0 1 1]] ->
[[1 1 0 1 0 1 1 1]
 [0 1 1 0 0 1 1 1]
 [1 1 1 0 1 1 1 1]
 [0 0 0 0 1 0 1 1]
 [0 1 1 0 1 1 0 0]]

[[0 1 0 0 0 0 1 0]
 [1 0 0 1 1 1 0 1]
 [1 1 1 1 0 0 0 0]
 [1 1 0 0 0 1 0 1]
 [1 0 0 1 0 0 1 1]] ->
[[0 0 1 1 1 0 0 0]
 [1 1 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 1]
 [0 1 0 0 0 0 0 1]
 [1 0 1 0 0 1 0 0]]

