# Analiza i projektiranje računalom - 4. laboratorijska vježba: demo crossover.py

## Priprema za izvođenje

In [1]:
import os

CD_KEY = "--HW04_D04_IN_ROOT"

In [2]:
if (
    CD_KEY not in os.environ
    or os.environ[CD_KEY] is None
    or len(os.environ[CD_KEY]) == 0
    or os.environ[CD_KEY] == "false"
):
    %cd ..
else:
    print(os.getcwd())
    
os.environ[CD_KEY] = "true"

/mnt/data/projekti/faks/AIPR/dz/dz-04


## Učitavanje paketa

In [3]:
import numpy as np

from src.evolution.crossover import (
    AveragingCrossover,
    ChooseOneCrossover,
    XORCrossover,
    XORTransformedCrossover,
)
from src.evolution.encoding import (
    BinaryEncoder,
    BinaryDecoder,
)

## Inicijalizacija

### Formatiranje

In [4]:
np.set_printoptions(precision=2, suppress=True)

### Konstante

In [5]:
n_specimen = 5

float_shape = 3

bits = 8
interval = (-1, 1)

### Jedinke

In [6]:
specimina = np.random.uniform(*interval, (n_specimen, float_shape))

### Koderi

In [7]:
be = BinaryEncoder(dim=8, interval=interval)
bd = BinaryDecoder(dim=8, interval=interval)

### Operatori

In [8]:
float_operators = [
    AveragingCrossover(interval=interval),
    ChooseOneCrossover(interval=interval)
]
binary_operators = [
    XORCrossover(),
    XORTransformedCrossover()
]

## Demonstracija

### Prikaz s pomičnom točkom

In [9]:
for float_operator in float_operators:
    print(f"Koristeći {float_operator}")
    
    for i in range(n_specimen - 1):
        chosen = specimina[i: i + 2]
        
        print(f"{chosen} -> {float_operator(chosen)}\n")
        
    print()

Koristeći AveragingCrossover operator
[[-0.76 -0.73 -0.05]
 [-0.29 -0.17 -0.33]] -> [[-0.52 -0.45 -0.19]]

[[-0.29 -0.17 -0.33]
 [-0.97  0.69  0.53]] -> [[-0.63  0.26  0.1 ]]

[[-0.97  0.69  0.53]
 [-0.21 -0.23  0.72]] -> [[-0.59  0.23  0.63]]

[[-0.21 -0.23  0.72]
 [ 0.01  0.38  0.54]] -> [[-0.1   0.08  0.63]]


Koristeći ChooseOneCrossover operator
[[-0.76 -0.73 -0.05]
 [-0.29 -0.17 -0.33]] -> [[-0.76 -0.73 -0.05]]

[[-0.29 -0.17 -0.33]
 [-0.97  0.69  0.53]] -> [[-0.29 -0.17 -0.33]]

[[-0.97  0.69  0.53]
 [-0.21 -0.23  0.72]] -> [[-0.97  0.69  0.72]]

[[-0.21 -0.23  0.72]
 [ 0.01  0.38  0.54]] -> [[-0.21 -0.23  0.72]]




### Prikaz u binarnom obliku

In [10]:
for binary_operator in binary_operators:
    print(f"Koristeći {binary_operator}")
    
    for i in range(n_specimen - 1):
        chosen = be(specimina[i: i + 2])
        
        print(f"{chosen} ->\n" + ("-" * 30) + f"\n{binary_operator(chosen)}\n\n")
        
    print()

Koristeći XORCrossover operator
[[[0 0 0 1 1 1 1 0]
  [0 0 1 0 0 0 0 1]
  [0 1 1 1 1 0 0 1]]

 [[0 1 0 1 1 0 1 0]
  [0 1 1 0 1 0 0 1]
  [0 1 0 1 0 1 0 0]]] ->
------------------------------
[[0 1 0 0 0 1 0 0]
 [0 1 0 0 1 0 0 0]
 [0 0 1 0 1 1 0 1]]


[[[0 1 0 1 1 0 1 0]
  [0 1 1 0 1 0 0 1]
  [0 1 0 1 0 1 0 0]]

 [[0 0 0 0 0 0 1 1]
  [1 1 0 1 0 1 1 0]
  [1 1 0 0 0 0 1 1]]] ->
------------------------------
[[0 1 0 1 1 0 0 1]
 [1 0 1 1 1 1 1 1]
 [1 0 0 1 0 1 1 1]]


[[[0 0 0 0 0 0 1 1]
  [1 1 0 1 0 1 1 0]
  [1 1 0 0 0 0 1 1]]

 [[0 1 1 0 0 1 0 0]
  [0 1 1 0 0 0 1 0]
  [1 1 0 1 1 0 1 1]]] ->
------------------------------
[[0 1 1 0 0 1 1 1]
 [1 0 1 1 0 1 0 0]
 [0 0 0 1 1 0 0 0]]


[[[0 1 1 0 0 1 0 0]
  [0 1 1 0 0 0 1 0]
  [1 1 0 1 1 0 1 1]]

 [[1 0 0 0 0 0 0 0]
  [1 0 1 1 0 0 0 0]
  [1 1 0 0 0 1 0 0]]] ->
------------------------------
[[1 1 1 0 0 1 0 0]
 [1 1 0 1 0 0 1 0]
 [0 0 0 1 1 1 1 1]]



Koristeći XORTransformedCrossover operator
[[[0 0 0 1 1 1 1 0]
  [0 0 1 0 0 0 0 1]
  [0 1 1 1 1